/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.4.2-10-g6e49bc3099"
#endif /* AVUTIL_FFVERSION_H */
